routes/web.php
<?php
use App\Events\event_PlayerDataChanged;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard','DashboardController@index')->name('index');
Auth::routes();
Route::get('/', function(){
    return view('home');
});
//Utilisateur routes
////////////////////////////////
Route::resource('utilisateurs','UtilisateurController');
Route::get('utilisateurs/{id}/droits','UtilisateurController@rights');
Route::post('utilisateurs/{id}/droits','UtilisateurController@updateRights');

//Group routes
////////////////////////////////
Route::resource('groups','GroupController');
Route::get('/groups/{id}/disposition','GroupController@disposition');
Route::post('/groups/{id}/disposition','GroupController@updateDispo');
Route::get('/groups/{id}/schedule','GroupController@editSchedule');
Route::post('/groups/{id}/schedule','GroupController@updateSchedule');



//Server configuration routes
////////////////////////////////
Route::get('/conf', 'ServerconfigController@index')->name('configure');
Route::post('conf', 'ServerconfigController@configure');
Route::get('/parameter','ServerconfigController@edit');
Route::post('/parameter','ServerconfigController@update');
//Player routes
////////////////////////////////
Route::resource('player','PlayerController',[
    'except' => ['show']
]);
Route::get('/player/login',function(){
    if(session('loggedinPlayer', 'null')=='null')   
        return view('player.login');
    else
        return view('player.playerhome');
});


Route::get('/player/home','PlayerController@home');
Route::get('/player/logout','PlayerController@logout');
Route::post('/player/login','PlayerController@login');
Route::get('/player/configure','PlayerController@manageConf');
Route::post('/player/configure','PlayerController@configure');
Route::get('/player/{id}/accept','PlayerController@accept');
Route::get('/player/{id}/dissociate','PlayerController@dissociate');
Route::get('/player/{id}/archive','PlayerController@archive');
Route::get('/player/{id}/disposition','PlayerController@disposition');
Route::post('/player/{id}/disposition','PlayerController@updateDispo');
Route::get('/player/{id}/mschedule','PlayerController@schedule');
Route::post('/player/{id}/mschedule','PlayerController@updateSchedule');
Route::get('/player/{id}/schedule','PlayerController@editSchedule');
Route::post('/player/{id}/seschedule','PlayerController@updateSchedule');
Route::get('/part','PlayerController@partindex');
Route::get('/part/{id}/edit','PlayerController@editPart');
Route::post('/part/{id}/edit','PlayerController@updatePart');
Route::get('/player/archived','PlayerController@archivedIndex');
Route::post('/player/home/check','PlayerController@checkIfChanged');
Route::post('/player/home/refresh','PlayerController@SendPlayerDataAjax');
Route::post('/player/processimage','PlayerController@processImage');
Route::post('/player/smart/change','PlayerController@changeMode');

Route::get('/overlay',function(){
    return view('player.overlay');
});
//Upload Media Routes
//////////////////////////////
Route::get('/multimedias','MultimediaController@index')->name('multimedia');
Route::get('/multimedias/upload','MultimediaController@create')->name('multimedia.upload');
Route::post('/multimedias/upload','MultimediaController@store');
Route::get('/multimedias/{id}/pub','MultimediaController@makePublic');
Route::get('/multimedias/{id}/pri','MultimediaController@makePrivate');
Route::get('/multimedias/{id}/del','MultimediaController@delete');
Route::post('/multimedia/tags/change','MultimediaController@changeTags');

//Sequence routes
/////////////////////////////
Route::resource('sequences','SequenceController');

Route::get('/cookietest',function(){
    return view('cookietest');
});
Route::get('/sequences/{id}/supperpose','SequenceController@overlay');
Route::post('/sequences/{id}/supperpose','SequenceController@changeOverlay');

//Schedule routes
////////////////////////////
Route::resource('schedules','ScheduleController');
Route::get('/schedules/{id}/createS','ScheduleController@createSchedule');
Route::post('/schedules/{id}/createS','ScheduleController@makeSchedule');
Route::get('/schedules/{id}/editS','ScheduleController@editSchedule');
Route::post('/schedules/{id}/editS','ScheduleController@updateSchedule');
Route::post('/schedules/getNewCal','ScheduleController@sendNewCalendar');

//custom add Routes
///////////////////////////
Route::resource('annonces','CustomController');

//Broadcasting routes
//////////////////////////
Route::get('/alertbox',function(){
    return view('Broadcasting.evenlistener');
});

Route::get('/fireEvent',function(){
    event(new event_PlayerDataChanged());
});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    //
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Group;
use App\Player;
use App\Disposition;
use App\Schedule;
use App\Events\event_PlayerDataChanged;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups=Group::All();
        return view('group.index',compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $players=Player::All();
        return view('group.create',compact('players'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'nom' => 'required|min:6',
        ]);
        
        $group=new Group();
        $group->name=$request->get('nom');
        $group->save();
        if($request->has('players'))
        {
            foreach($request->get('players') as $player)
            {
                $player=Player::find($player);
                $player->group_id=$group->id;
                $player->save();
            }
        }
        return redirect('groups')->with('success','Groupe creé');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response 
     */
    public function edit($id)
    {
        $group=Group::find($id);
        $players=Player::All();
        return view('group.edit',compact('group','players','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'nom' => 'required|min:6',
        ]);
        $players=Player::All();
        $group=Group::find($id);
        $group->name=$request->get('nom');
        $group->save();
        $id=$group->id;
        foreach($players as $player)
        {
            $myBool=false;
            if($request->has('players'))
            {
                foreach($request->get('players') as $pla)
                {
                    $playertemp=Player::find($pla);
                    error_log($pla.' - '.$player->id);
                    if($player->id==$playertemp->id)
                    {
                        $player->group_id=$id;
                        $myBool=true;
                        break;
                    }
                }
                if($myBool==false)
                {
                    error_log($player->id);
                    $player->group_id=-1;
                }
            }
            
            $player->save();
        }
        
        return redirect('groups')->with('success','Groupe modifié');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $group=Group::find($id);
        $group->delete();
        return redirect()->route('groups.index')->with('success','Groupe supprimé');
    }

    public function disposition($id)
    {
        $group=Group::find($id);
        return view('group.disposition',compact('group','id'));
    }

    public function editSchedule($id)
    {
        $group=Group::find($id);
        $schedules=Schedule::All();
        return view('group.schedule',compact('schedules','group','id'));
    }

    public function updateDispo(Request $request,$id)
    {
        $dispos=Disposition::All();
        $players=Player::All();

        foreach($players as $player)
        {
            if($player->group_id==$id)
            {
                foreach($dispos as $dispo)
                {
                    if($dispo->player==$player->id)
                    {
                        $dispo->delete();
                    }
                }
                $dispo =new Disposition();
                $dispo->player=$player->id;
                $dispo->pos=$request->get('pos');
                $dispo->text1=$request->get('txt1');
                $dispo->text2=$request->get('txt2');
                $dispo->type=$request->get('type');
                $dispo->save();
                app('App\Http\Controllers\PlayerController')->storeChangelog($player->id);
            }
        }
        event(new event_PlayerDataChanged());
        return redirect('groups')->with('success','Disposition modifié');
    }

    public function updateSchedule(Request $request,$id)
    {
        $players=Player::All();

        foreach($players as $player)
        {
            if($player->group_id==$id)
            {
                $player->schedule=$request->get('schedule');
                $player->save();
                app('App\Http\Controllers\PlayerController')->storeChangelog($player->id);
            }
        }
        event(new event_PlayerDataChanged());
        return redirect('groups')->with('success','schedule modifié');
    }
}

resources/views/group/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container bg-light my-5 py-3" >
        <h2>Creation des groupes</h2><br/>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="post" action="{{url('groups')}}">
            @csrf
            {{csrf_field()}}
            
            <div class="container border">
                <br>
                <div class="form-group">
                    <label for="nom">Nom</label>
                    <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom" >
                </div>
                <div class="form-group">
                    <label for="player">Players</label>
                    <select class="form-control" name="players[]" id="player" multiple>
                        @foreach($players as $player)
                        <option value="{{$player->id}}">{{$player->nom}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-primary mb-2">Creer</button>
        </form>
    </div>
@endsection

resources/views/group/disposition.blade.php
@extends('layouts.app')

@section('content')
    <div class="container bg-light my-5 py-3" >
        <h2>Disposition group </h2><br/>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="post" action="{{action('GroupController@updateDispo',$id)}}">
            @csrf
            <div class="container border">
                <div class=" mx-auto">
                    <select name="" id="layout">
                        <option data-img-class="first" data-img-alt="Séquence seule" value="0" data-img-src="{{ asset('images/Sequence-Seul.png') }}">Default</option>
                        <option data-img-alt="Séquence avec une bande avec texte défilant" value="1" data-img-src="{{ asset('images/Sequence-Seul-Bar.png') }}">Single bar</option>
                        <option data-img-alt="Séquence avec deux bandes" value="2" data-img-src="{{ asset('images/Sequence-Seul-Deux-Bar.png') }}">Two bars</option>
                        <option data-img-alt="Quatre séquences publicitaires simultanément" value="3" data-img-src="{{ asset('images/Sequence-Quatres.png') }}">Four sequences</option>
                     
                    </select>
                </div>
                <div class="form-group" id="pos">
                    <label for="pos">Position bande</label>
                    <select name="pos" id="pos" class="form-control">
                        <option value="0">top</option>
                        <option value="1">bot</option>
                    </select>
                </div>
                <div class="form-group" id="txt1">
                    <label for="topbar">Text bande</label>
                    <input type="text" name="txt1" id="topbar" class="form-control" >
                </div>
                <div class="form-group" id="txt2">
                    <label for="botbar">Text deuxieme bande</label>
                    <input type="text" name="txt2" id="botbar" class="form-control" >
                </div>
                <input type="hidden" name="type" id="type" >
                    
            </div>
            <br>
            <button type="submit" class="btn btn-primary mb-2">Modifier</button>
        </form>
    </div>
    <script>

        $("#layout").imagepicker({
            show_label: true
            });
            $('#pos').hide();
            $('#txt1').hide();
            $('#txt2').hide();

            $('#layout').on('change', function() {
                if( this.value == 1)
                {
                    $('#pos').show(300);
                    $('#txt1').show(300);
                    $('#txt2').hide(300);
                    $('#type').val(1);
                }
                else if(this.value == 2)
                {
                    $('#pos').hide(300);
                    $('#txt1').show(300);
                    $('#txt2').show(300);
                    $('#type').val(2);
                }
                else if(this.value == 0)
                {
                    $('#pos').hide(300);
                    $('#txt1').hide(300);
                    $('#txt2').hide(300);
                    $('#type').val(0);
                }
                else
                {
                    $('#pos').hide(300);
                    $('#txt1').hide(300);
                    $('#txt2').hide(300);
                    $('#type').val(4);
                }
            });
        $( document ).ready(function() {
            var slctedval = $('#layout').val();
            if(slctedval==1)
            {
                $('#pos').show(300);
                $('#txt1').show(300);
                $('#txt2').hide(300);
                $('#type').val(1);
            }
            else if(slctedval==2)
            {
                $('#pos').hide(300);
                $('#txt1').show(300);
                $('#txt2').show(300);
                $('#type').val(2);
            }
            else if(slctedval==0)
            {
                $('#pos').hide(300);
                $('#txt1').hide(300);
                $('#txt2').hide(300);
                $('#type').val(0);
            }
            else 
            {
                $('#pos').hide(300);
                $('#txt1').hide(300);
                $('#txt2').hide(300);
                $('#type').val(4);
            }
        });
    </script>
@endsection

resources/views/group/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container bg-light my-5 py-3" >
        <h2>Modification du groupe</h2><br/>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="post" action="{{action('GroupController@update',$id)}}">
            @csrf
            <input name="_method" type="hidden" value="PATCH">
            
            <div class="container border">
                <br>
                <div class="form-group">
                    <label for="nom">Nom</label>
                <input type="text" class="form-control" id="nom" name="nom" value="{{$group->name}}" >
                </div>
                <div class="form-group">
                    <label for="player">Players</label>
                    <select class="form-control" name="players[]" id="player" multiple>
                        @foreach($players as $player)
                        <option value="{{$player->id}}" @if($player->group_id == $group->id)selected="selected"@endif >{{$player->nom}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-primary mb-2">Modifier</button>
        </form>
    </div>
@endsection

resources/views/group/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content mt-3">
    @if (\Session::has('success'))
        <div class="alert alert-success alert-dismissible">
            <p>{{ \Session::get('success') }}</p>
        </div><br />
    @endif
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Data Table</strong>
                        <a href="{{ route('groups.create') }}" class="float-right btn btn-primary">Creer groupe</a>
                    </div>
                    <div class="card-body">
                        <table id="bootstrap-data-table" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nom</th>
                                    <th>-</th>
                                    <th>-</th>
                                    <th>-</th>
                                    <th>-</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($groups as $group)
                                <tr>
                                    <td>{{$group['id']}}</td>
                                    <td>{{$group['name']}}</td>
                                    <td>
                                        <a href="{{action('GroupController@editSchedule', $group['id'])}}" class="btn btn-dark">Modifier planning</a>
                                    </td>
                                    <td>
                                        <a href="{{action('GroupController@disposition', $group['id'])}}" class="btn btn-success">Disposition</a>
                                    </td>
                                    <td><a href="{{action('GroupController@edit', $group['id'])}}" class="btn btn-warning">Modifier</a></td>
                                    <td>
                                    <form action="{{action('GroupController@destroy', $group['id'])}}" method="post">
                                        @csrf
                                        <input name="_method" type="hidden" value="DELETE">
                                        <button class="btn btn-danger" type="submit">Supprimer</button>
                                    </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/group/schedule.blade.php
@extends('layouts.app')

@section('content')
<div class=" container bg-light">
    <h3 class="my-3 text-center">Groupe planning</h3>
    <div class="animated fadeIn">
        <div class="row p-3">
            <div class="col-8 py-3 offset-2">
                <form action="{{action('GroupController@updateSchedule',$id)}}" method="post">
                    @csrf
                    <select class="form-control" name="schedule">
                        @foreach($schedules as $schedule)
                            <option value="{{$schedule->id}}">{{$schedule->name}}</option>
                        @endforeach
                    </select>
                    <button type="submit" class="btn btn-primary my-3">Affecter</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection